### ISSUE TITLE
グラフに範囲指定をするスライダーを追加する

### ISSUE THREAD

**Issue by HyodaKazuaki** [nomunomu0504/covid19#119]
## 改善詳細 / Details of Improvement
- グラフに表示されている期間のうち、初期は値がないためグラフの範囲を変更することができるスライダーを追加する
    - 参考: [北海道 新型コロナウイルスまとめサイト](https://stopcovid19.hokkaido.dev/)

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/17569894/78628197-73d29c80-78ce-11ea-95bf-5d0adc934afe.png)

## 期待する見せ方・挙動 / Expected behavior
- グラフの範囲が変更可能なスライダーを追加する

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by stshsn** [comment]
やってみます。
