### ISSUE TITLE
県の公開したオープンデータに対応させる

### ISSUE THREAD

**Issue by HyodaKazuaki** [nomunomu0504/covid19#126]
## 改善詳細 / Details of Improvement
- 福井県が公開したオープンデータからデータを取得するようにする

## 期待する見せ方・挙動 / Expected behavior
- オープンデータに追従し正確かつ高速に情報を提供できるようにする

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by HyodaKazuaki** [comment]
## TODO
* ~~スクリプトが生成する各jsonに入っているdateがUTCなのでJSTに変更する~~
* 自宅療養などのデータが公開されたらそのデータを差し込む(コンポーネント復帰 #135 )

**Comment by nomunomu0504** [comment]
これはもう対応できてる感じ？
@HyodaKazuaki

**Comment by HyodaKazuaki** [comment]
各病状のデータは公開されていないので完璧とは言えないですね
その部分だけ切り出して別のIssueにしちゃいますか

**Comment by HyodaKazuaki** [comment]
新しいIssueを発行したのでこちらはCloseします
