### ISSUE TITLE
"陽性患者の属性" 表に異常なデータがある

### ISSUE THREAD

**Issue by mimikun** [nomunomu0504/covid19#12966]
## 起こっている問題 / The Problem

- "陽性患者の属性" 表に
  - "発症日" が Invalid Date
  - "発症日" が "---" で, 以降が空欄

となっている箇所があります

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/13450321/149736432-06cb8f74-613b-467f-be0b-56d79f083e4c.png)

## 期待する見せ方・挙動 / Expected Behavior

- Invalid Date の場合, "不明" や "---"とする
- 発症日以降空欄の場合, 表に出さない

## 起こっている問題の再現手段 / Steps to Reproduce

1. ブラウザで https://covid19-fukui.com にアクセスする
2. "陽性患者の属性" 表を見る
3. 見えなければしばらくスクロールしていく

## 動作環境・ブラウザ / Environment

- Windows, iOS
- Chrome. Safari

**Comment by HyodaKazuaki** [comment]
これは、[福井県が公開している新型コロナウイルス感染症のオープンデータ](https://www.pref.fukui.lg.jp/doc/toukei-jouhou/covid-19.html)の陽性患者属性ファイルに誤った入力が行われていることが原因だと思われます。

```
// 省略 //
3615,180009,福井県,,2022/1/17,2022/1/15,敦賀市,20代,男性,アルバイト,,,0,,
3616,180009,福井県,,2022/1/17,―,越前市,70代,女性,無職,,,0,,
3617,180009,福井県,,2022/1/17,2022/1/15,鯖江市,50代,男性,会社員,,,0,,
// 省略 //
```

2件目の6項目目について、不明な場合は記入の必要はないのですが、"―"が入っているためInvalid Dateと表示されています。
たまにこのようなことが発生してしまい、自動でデータを取得し更新を行っているサイトが影響を受けている状況です。
誤ったフォーマットのデータを処理する必要があるのですが、誤り方は多種多様なので難しい所ではないかと思います。
例えば、担当者向けの更新方法に関するメモ書きが挿入されたまま残っていることもあります。
暫定的な対応としては、 @mimikun が期待する見せ方・挙動 に記載されたように、Invalid Dateの場合などと例外分けするのがいいかもしれません。
または、福井県の担当者の方に修正をお願いするかでしょうか？ @nomunomu0504

**Comment by h-nomura0504** [comment]
@mimikun さん、連絡・issue作成ありがとうございます！開発者の野村です🙇‍♂

ひとまず、県の担当者に連絡は入れてみようと思います。
@HyodaKazuaki も含めたグループチャットを作成した方がよいですかね。自分が最近本業の方で担当できなくなってきてしまっているので...。

**Comment by mimikun** [comment]
@HyodaKazuaki 
詳細な情報をありがとうございます。
県のほうでフォーマットを統一できるなら、県の担当者の連絡を待ってから決めたほうが良いでしょうね…

この問題の影響度がどれくらいか分かりませんが、暫定で直して、後から本格修正を入れるのも手かな、と思います
