### ISSUE TITLE
それぞれのデータを個別のJSONで管理（スクレイピング含む）

### ISSUE THREAD

**Issue by nomunomu0504** [nomunomu0504/covid19#13]
## 改善詳細 / Details of Improvement
- 現状、複数カードのデータが同じJSONファイルにまとめられているので、今後自動更新化を考えた場合、1対1対応で管理した方がいい

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by HyodaKazuaki** [comment]
JSONファイルの分離やってみます

**Comment by HyodaKazuaki** [comment]
`covid19_fukui/covid19_fukui.json`と`data/data.json`がありますが両方ともそれぞれのデータで分離した方がいいですか？
