### ISSUE TITLE
緊急事態宣言解除への対応

### ISSUE THREAD

**Issue by stshsn** [nomunomu0504/covid19#1335]
## 改善詳細 / Details of Improvement
- 速報カードにある「緊急事態宣言」へのリンクボタンのリンク先ページから緊急事態に関する内容が無くなっている
- リンクボタンの文言もそれに合わせて変更したい
- もしくはボタンを削除したい

### リンク先ページの内容
<img width="958" alt="image" src="https://user-images.githubusercontent.com/34150349/82217283-2e859e00-9955-11ea-9494-901702709c45.png">

## 期待する見せ方・挙動 / Expected behavior
- ボタンの文言を適切に修正する
- もしくはボタンを削除する

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by HyodaKazuaki** [comment]
緊急事態宣言は解除されたのでボタン自体を削除する方針でいいと思います

**Comment by stshsn** [comment]
ボタン削除の方針で対応します
