### ISSUE TITLE
サイトのテーマカラーを福井県のイメージカラーにする

### ISSUE THREAD

**Issue by HyodaKazuaki** [nomunomu0504/covid19#149]
## 改善詳細 / Details of Improvement
- 現在のサイトは東京都のイメージカラーで構成されているため、福井県らしいサイトのカラーとは言えない
- サイトのテーマカラーに福井県のイメージカラーを採用し、県の公式サイトとの調和を図る

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/17569894/78821503-8fe05600-7a14-11ea-85ce-37040c8a9697.png)

## 期待する見せ方・挙動 / Expected behavior
- 福井県のイメージカラーを使う
- 具体的な色については募集中です
    - このIssueにコメントとして案を載せてもらえると嬉しいです

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by nomunomu0504** [comment]
そもそも福井県のイメージカラーが、何色なんか分からん

**Comment by HyodaKazuaki** [comment]
福井県のサイトに使われているカラーコードは`#0054c6`です

**Comment by nomunomu0504** [comment]
対応します

**Comment by nomunomu0504** [comment]
一通り、福井県の色合いに調整できたのでcloseします
