### ISSUE TITLE
感染症病床使用率が実際と異なる

### ISSUE THREAD

**Issue by HyodaKazuaki** [nomunomu0504/covid19#160]
## 起こっている問題 / The Problem
- サイトに表示される感染症病床使用率は実際の感染症病床使用率と異なる

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/17569894/78888682-16407a80-7a9d-11ea-8274-2b0701dbafe3.png)

## 期待する見せ方・挙動 / Expected Behavior
- オープンデータに自宅療養者数、宿泊施設入所者数、入院者数を追加する
- 参考値であることを注釈として追加する

## 起こっている問題の再現手段 / Steps to Reproduce
1. サイトにアクセスする

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by nomunomu0504** [comment]
現状は、注釈を入れることで対応

**Comment by nomunomu0504** [comment]
県発表のデータを採用することにして、この件はClose
