### ISSUE TITLE
SEO対策を施したい

### ISSUE THREAD

**Issue by nomunomu0504** [nomunomu0504/covid19#19]
## 改善詳細 / Details of Improvement
- 現状、SNSからの流入がアクセスの約8,9割を占めている。検索エンジンからの流入がほどんどないのでSEO対策を施したい

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by satackey** [comment]
SEO全然詳しくはないのですが、`www`あり/なしの混在は統一した方が良さそうですね。
Cloudflareで簡単に設定できるので、どちらか決めて頂ければ修正します！

**Comment by nomunomu0504** [comment]
`www` は今まで使っていなかったので、ない方に統一できれば！

**Comment by satackey** [comment]
おっけーです:+1:

**Comment by satackey** [comment]
設定完了しました。
リダイレクトされるはずです → <http://www.covid19-fukui.com>

**Comment by nomunomu0504** [comment]
お、確認できた！ありがとう！

このリポジトリのコラボレーターへのインバイト送っておきましたー

**Comment by nomunomu0504** [comment]
なんだかんだアクセス数も増えて、流入も増えているので、SEO対策は今ところ、大丈夫そうなのでclose
