### ISSUE TITLE
自動でデータの更新を行う

### ISSUE THREAD

**Issue by satackey** [nomunomu0504/covid19#190]
## 改善詳細 / Details of Improvement
- 現在は手動でCSV等のデータを取得するGitHub ActionsのWorkflowを起動しているが、定期的に自動で実行させたい

## 期待する見せ方・挙動 / Expected behavior
- 定期的にGitHub ActionsのWorkflowからデータ更新のPRを作成します
- ↓のBotを導入し、自動でマージを行います
  - https://github.com/nzws/auto-merge-bot

**Comment by satackey** [comment]
@nomunomu0504 更新の頻度はどれくらいがいいですかね？

**Comment by nomunomu0504** [comment]
そうねー。更新時間の基準は0:00からn分毎って感じの設定？

**Comment by satackey** [comment]
cronと同じです！(`@hourly`みたいな non-standard syntax は使えないようですが)

**Comment by nomunomu0504** [comment]
あー理解した！
とりあえず1時間毎でいい気がするけど多いかな（24commits / day）

**Comment by satackey** [comment]
OKです 🙆‍♂️

**Comment by nomunomu0504** [comment]
頼みます！！
