### ISSUE TITLE
Youtube API key の変更/設定ファイルの分離

### ISSUE THREAD

**Issue by stshsn** [nomunomu0504/covid19#28]
## 起こっている問題 / The Problem
- Youtube API key が開発用に利用しているもののためアクセス上限に達してしまう

## スクリーンショット / Screenshot
![screenshot](https://user-images.githubusercontent.com/34150349/77823444-9b8f6b00-713e-11ea-82e5-d3c0a59c559f.png)
![devtools](https://user-images.githubusercontent.com/34150349/77823452-a64a0000-713e-11ea-9ee8-2cb5a640a59a.png)

## 期待する見せ方・挙動 / Expected Behavior
- API key を適切なものに差し替えてください

## 起こっている問題の再現手段 / Steps to Reproduce
1. covid19-fukui.com にアクセス
2. Youtubeカードのコンテンツが正しく表示されない
3. consoleで www.googleapis.com へのアクセスが403となる

## 動作環境・ブラウザ / Environment
- Any OS
- Any browser

**Comment by FooQoo** [comment]
@stshsn 
403に関しては、アクセスのたびにAPIを叩いてしまうので上限に引っかかるような気がします。
可能であればキャッシュに入れて、一日一回更新のような形がよいかと思います。

**Comment by nomunomu0504** [comment]
ありがとうございます！！
API Keyが開発者用を利用しているとのこと、了解しました。

ちなみに、開発者用ではなく、商用？だといくらぐらいになるのでしょう。詳細が記載されているリンクなどいただけると助かります！

**Comment by stshsn** [comment]
対応ありがとうございます。
こちらもあまり詳しくないので価格などについてはよくわかっていないのが正直なところです。
Youtube Data API のアクセス上限数などについては、以下のURLが見つかりました。
https://developers.google.com/youtube/v3/getting-started?hl=ja

API Keyはソースに含めるべきではなかったようですね。今後気をつけます。

**Comment by HyodaKazuaki** [comment]
YouTube Data API(v3)はアクセス上限にクォータという単位を使っているようです
各処理でこのクォータがどれぐらい消費されるかは以下のサイトで計算できます
https://developers.google.com/youtube/v3/determine_quota_cost
以下のリンクから申請するとクォータの上限を上げることができるみたいです
ただ、金額は具体的には提示していないようです
もしかすると無料なのかもしれませんがわかりません(コロナウイルス関連といえば無料になるかも？)
https://support.google.com/youtube/contact/yt_api_form?hl=en

## 参考
https://support.google.com/youtube/thread/9238731?hl=ja
https://teratail.com/questions/196188

**Comment by stshsn** [comment]
バックエンド側でスクレイピングなどのために、定期的に動いているコードはどれになるのでしょうか？
アプリケーション全体の仕組みが理解できていないので教えてもらいたいです。

**Comment by nomunomu0504** [comment]
@HyodaKazuaki 
ありがとう！一旦確認して、連絡できるようであれば連絡してみます！！

@stshsn 
covid19_fukui配下にある covid19fukui.js になります。
