### ISSUE TITLE
検査陽性者の状況が不正確

### ISSUE THREAD

**Issue by HyodaKazuaki** [nomunomu0504/covid19#3]
## 起こっている問題 / The Problem
- 検査陽性者数の状況の入院中について、1名入院中のはずが0名となっている(ソース: https://www.pref.fukui.lg.jp/doc/kenkou/kansensyo-yobousessyu/corona_d/fil/200319-1.pdf)
- 検査陽性者数の状況の軽症・中等症について、1名のはずが0名となっている(ソース: https://www.fukuishimbun.co.jp/articles/1050670) 

## スクリーンショット / Screenshot
![situation](https://user-images.githubusercontent.com/17569894/77330603-ef770a00-6d62-11ea-81b9-92b2f92447e1.png)

## 期待する見せ方・挙動 / Expected Behavior
- 入院中人数を1名にする
- 軽症・中等症人数を1名にする

## 起こっている問題の再現手段 / Steps to Reproduce
1. [Webサイトトップページ](https://covid19-fukui.com/)を開く

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by nomunomu0504** [comment]
PR発行先のブランチ変更をお願いします！

**Comment by nomunomu0504** [comment]
margeしたのでcloseします
