### ISSUE TITLE
vue-i18nのwarnをsilentにする

### ISSUE THREAD

**Issue by FooQoo** [nomunomu0504/covid19#30]
## 起こっている問題 / The Problem
- 開発環境で `yarn dev` を実行すると、 `vue-i18n` のwarnが大量に出る
- 現状このwarnは深刻でないと判断し、silentモードにして、warnが出ないようにしたい

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/14051784/77840010-83aafc00-71bd-11ea-901a-6609ab8bb1df.png)

## 期待する見せ方・挙動 / Expected Behavior
- warnが出ないようにする

## 起こっている問題の再現手段 / Steps to Reproduce
1. yarn dev
2. `http://localhost:3000/` にアクセス
3. サーバーのログに上記warnが出る

## 動作環境・ブラウザ / Environment
- macOS
- Chrome 

## 参考
https://github.com/kazupon/vue-i18n/issues/201

**Comment by FooQoo** [comment]
@nomunomu0504 
こちらfeatureブランチをpushをしようとした際、`permission denied`されてました。
push権限が開放されてるか、確認お願いできますでしょうか？

![image](https://user-images.githubusercontent.com/14051784/77840201-af2ee600-71bf-11ea-8fab-4089f5561bee.png)

**Comment by nomunomu0504** [comment]
対応ありがとうございます！

直接、リポジトリへのpushは許可しておりません。基本的にはリポジトリをforkして、PRを発行してもらう形になります。

よろしくお願いいたします
