### ISSUE TITLE
Google Analyticsの導入

### ISSUE THREAD

**Issue by FooQoo** [nomunomu0504/covid19#33]
## 改善詳細 / Details of Improvement
- アクセス解析のためにGoogle Analyticsを導入する
- - 具体的にはhtml headerにGA用のJSを埋め込む
- - nuxt特有の方法があるか要調査

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

## 相談
- 誰のアカウントでGAを運用するか？
- 特に指定なければFooQooのアカウントを使っても良いか？

**Comment by nomunomu0504** [comment]
ありがとうございます。Google Analyticsはサイト公開時からすでに導入しており、私のアカウントを用いています！
