### ISSUE TITLE
緊急事態宣言発令中の表記を出す

### ISSUE THREAD

**Issue by HyodaKazuaki** [nomunomu0504/covid19#359]
## 改善詳細 / Details of Improvement
- 県内で緊急事態宣言が発令されたため、これを示す表記を追加すべき

## スクリーンショット / Screenshot
東京都での例
![image](https://user-images.githubusercontent.com/17569894/79297681-d86aa880-7f19-11ea-9b43-2d959324c2cb.png)

## 期待する見せ方・挙動 / Expected behavior
- 「福井県緊急事態宣言について」などの文章に該当PDFファイルをリンクする

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by stshsn** [comment]
対応します
