### ISSUE TITLE
検査実施人数の全体累計の期間表示がおかしい

### ISSUE THREAD

**Issue by HyodaKazuaki** [nomunomu0504/covid19#36]
## 起こっている問題 / The Problem
- 検査実施人数を累計にした場合の期間表示がおかしい

## スクリーンショット / Screenshot
![検査実施人数](https://user-images.githubusercontent.com/17569894/77848936-0609df00-7203-11ea-9510-a0678259649d.png)

## 期待する見せ方・挙動 / Expected Behavior
- 現在の場合は`3/23 ~ 3/29の全体累計`でなく`2/17 ~ 3/29の全体累計`と表示されるべき

## 起こっている問題の再現手段 / Steps to Reproduce
1. サイトにアクセスする
2. 検査実施人数カードを見る
3. 検査実施人数カードを累計表示にする

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by nomunomu0504** [comment]
そうなってくると、期間の表記がいらないかなーって感じやな。

「全体累計」って表示されるだけで問題なさそう。対応できそうならアサインします！

**Comment by HyodaKazuaki** [comment]
とすると、週別での表記は「今週の合計」ですかね？
27 を対応してもらえるとこっちに移れそうです！

**Comment by nomunomu0504** [comment]
週別はそんな感じになるかと思います！

27については、まだ確認終わってないんですが、コードを見た感じ大丈夫だと思います。
なので、こちらを対応してもらって大丈夫です！、もし不具合あればこちらで対応できると思います！

**Comment by HyodaKazuaki** [comment]
了解です！
じゃあアサインお願いします

**Comment by nomunomu0504** [comment]
@HyodaKazuaki 
お願いします！
