### ISSUE TITLE
福井県のLINE公式アカウントのアイコン追加

### ISSUE THREAD

**Issue by FooQoo** [nomunomu0504/covid19#37]
## 改善詳細 / Details of Improvement
- 東京都に倣い、LINEの友達登録を行うアイコンを追加する
- 東京都の実装をコピーしてくる

## スクリーンショット / Screenshot
実装イメージ
![image](https://user-images.githubusercontent.com/14051784/77850172-a6fc9800-720b-11ea-826f-43975bd5ae7d.png)

## 期待する見せ方・挙動 / Expected behavior
PC版：QRコードリンクに遷移
SP版：LINEアプリに飛び、友達追加申請の画面に移る

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

## 参考
- [東京都版](https://stopcovid19.metro.tokyo.lg.jp/flow)
- [福井県のLINEアカウントについて](https://www.pref.fukui.lg.jp/doc/kenkou/corona/coronaline.html)

**Comment by nomunomu0504** [comment]
ありがとうございます。LINE以外のアイコンは全て僕のアカウントへのリンクになってます。

なので、そこに福井県のLINEアカウントを掲載するのはUI/UX的にちょっと考える必要があるかと思います。

一応、別イシューでフローを作るとあるので、フローの部分に含められるのであれば、そちらで吸収したいかな。というのが、率直な感想です。

他の解決方法などあれば、ぜひコメントください！

**Comment by HyodaKazuaki** [comment]
福井県の各種SNSのアカウントがあるのでそちらに差し替えるのは一つの方法だと思いますが、このサイトは今のところ非公式なのでリンク先としては不適なんですよね

## 例
* [福井県庁　危機対策・防災課(Twitter)](https://twitter.com/kikitaisaku)
* [ほやほや福井（福井県広報広聴課）(Facebook)](https://www.facebook.com/hoyahoyafukui/)

できれば県の方にこのサイトを認識してもらって、何かリアクションを起こしてもらえるといいかもしれませんがどうでしょう？

**Comment by nomunomu0504** [comment]
そうなんです。なので今のところは開発者である、僕のアカウントへのリンクとなっています。

一応なんですが、県の方とすでに連絡は取り合っている状況です。が、県の公式にするまでには色々と時間がかかるのと、難しい部分もあるみたいなので、今すぐ公式にというのは難しそうでした。（今後も話し合いは続けていく予定です）

**Comment by FooQoo** [comment]
@nomunomu0504 @HyodaKazuaki 
議論いただきありがとうございます。
公式アカウントのアイコン表示に関しては、以下画像のような誘導文句で可能かなと考えておりますが、いかがでしょうか？
![image](https://user-images.githubusercontent.com/14051784/77853756-cbaf3a80-7220-11ea-9a9b-246c08134bfa.png)

上記に関して、グレーゾーンということであれば、こちらのissueは一旦保留で構わないと思います。

**Comment by nomunomu0504** [comment]
@FooQoo 

提案ありがとうございます。一旦、県の担当の方にこの件に関して問い合わせてみます。その回答に応じて、本サイトの対応を考えたいと思います！
なので、正式な回答があるまで、このissueはpendingということにします。

提案ありがとうございました！

**Comment by nomunomu0504** [comment]
とりあえず県管轄のSNSへのリンクは必要なさそうなのでClose
