### ISSUE TITLE
フローページの追加

### ISSUE THREAD

**Issue by FooQoo** [nomunomu0504/covid19#38]
## 改善詳細 / Details of Improvement
- [新型コロナ感染症が心配なときに](https://stopcovid19.metro.tokyo.lg.jp/flow)のようなフローページの作成
- [福井県のHPのフロー画像](https://www.pref.fukui.lg.jp/doc/kenkou/kansensyo-yobousessyu/corona_d/img/004.jpg)を参考にフローページのUIを作成する

## 期待する見せ方・挙動 / Expected behavior
- UIは東京都を参考

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by nomunomu0504** [comment]
やはりあった方がいいですかね。今のところ福井県の公式サイトにリンクを飛ばしているんですが🤔

**Comment by FooQoo** [comment]
@nomunomu0504 
あって悪いことはないかと思いますが、実装コストが高ければ優先度は低いと思います。
一旦東京都のサイトを参考に実装してみて、難しいようならcloseしようと思いますmm

**Comment by nomunomu0504** [comment]
分かりました！このissueにassignしておきます！

もし、詰まるところがあれば連絡頂けると対応できるかも知れません！

よろしくお願いします！🙇‍♂️
