### ISSUE TITLE
陽性患者数の累計などがわかるグラフを表示する

### ISSUE THREAD

**Issue by HyodaKazuaki** [nomunomu0504/covid19#42]
## 改善詳細 / Details of Improvement
- 東京都の新型コロナウイルス感染症対策サイトにある陽性患者数のカードと同等のものを復活させる

## スクリーンショット / Screenshot
![陽性患者数](https://user-images.githubusercontent.com/17569894/77909123-bb9e6600-72c7-11ea-8cfa-b302924272d5.png)

## 期待する見せ方・挙動 / Expected behavior
- [陽性患者数 | 東京都 新型コロナウイルス感染症対策サイト](https://stopcovid19.metro.tokyo.lg.jp/cards/number-of-confirmed-cases/)のグラフと同じような表示を行う

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by nomunomu0504** [comment]
そうやなー、そろそろこれを復活させた方がよろしいかもですな

**Comment by nomunomu0504** [comment]
もし対応できそうならassignします！

**Comment by HyodaKazuaki** [comment]
お願いします
とりあえず復活はできたのでいったんPR出しますがちょっと問題があります
詳しくはPRの方で！
