### ISSUE TITLE
スクレイピングから取得してるデータ以外をスプレッドシートで管理

### ISSUE THREAD

**Issue by nomunomu0504** [nomunomu0504/covid19#48]
## 改善詳細 / Details of Improvement
- 現状、福井県のサイトからスクレイピングしているデータ以外は手動でJSONを更新している。変更があるたびにJSONを更新してビルドをかけているので、更新に時間がかかる。

- そのため、Googleのスプレッドシートを用いてデータを管理し、そこからJSONデータを構築して表示させたい。更新頻度は30min/回（42回/日）

- 緊急更新時の時に強制反映させる方法がないかを模索中

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by nomunomu0504** [comment]
サーバーサイドでは Request の method が GET, POST 以外にも PUT, PATCH を取得することができたので、更新したら専用のURLを叩いて更新させるという方法が使えるかもしれないので、模索中...

**Comment by FooQoo** [comment]
@nomunomu0504 
ぜひやっていきましょう！
簡単な処理の流れは以下のようなCLIでしょうか。

1. サーバでgoogleapiを叩き、スプレッドシートのデータを取得する
2. 取得したデータをjsonファイルとして、指定のフォルダに保存

googleapi周りはこちらが参考になりそうです！
- [Googleスプレッドシートをプログラムから操作](https://qiita.com/howdy39/items/ca719537bba676dce1cf)

**Comment by HyodaKazuaki** [comment]
このプロジェクトはSlackのワークスペースを運用しているので、Slackからチャットコマンドで更新をかける方法はどうでしょう？
エラーなども専用のチャンネルに吐き出せばいいんじゃないかと

**Comment by nomunomu0504** [comment]
なるほど。更新のデータ転送の方法とフローをkwsk

**Comment by HyodaKazuaki** [comment]
Slackの方法はあくまでもサイトの更新(スプレッドシートを取得してjsonに変換し保存する)に使える程度になるんじゃないかと思っています
スプレッドシート自体の更新方法は別ですね

例えば、
1. Slackの専用のチャンネルで`update`などのコマンドメッセージをチャット
2. 同チャンネルに参加しているBotはコマンドメッセージを受け取りGoogleAPIなどでスプレッドシートのデータを取得
3. 取得したデータをJSON形式に変換し保存またはSlackチャンネルに投稿(リポジトリにコミットでもいいかも)

**Comment by nomunomu0504** [comment]
なるほど。

できれば人間はスプレッドシートだけを更新して、あとはBot系が全てやってくれるのがベストなんだなー。

**Comment by nomunomu0504** [comment]
Vueでサーバーコマンドを実行するようなプラグインというかライブラリとかってないかな。

そもそもそんなことできないか🤔（APIとかだとできるかなと思ったんだが）

**Comment by HyodaKazuaki** [comment]
> できれば人間はスプレッドシートだけを更新して、あとはBot系が全てやってくれるのがベストなんだなー。

Googleのスプレッドシートは変更をメールで通知する機能があるので、メールを受信したらBotが動き出すようにすればいけるかもですね

VueというよりJavaScriptやTypeScriptはシェルコマンドを実行できるようです
https://tkybpp.hatenablog.com/entry/2016/04/25/163246

**Comment by nomunomu0504** [comment]
それなら、JSとかでcron設定して動作させるのが濃厚かな〜
> そのため、Googleのスプレッドシートを用いてデータを管理し、そこからJSONデータを構築して表示させたい。更新頻度は30min/回（42回/日）

**Comment by HyodaKazuaki** [comment]
新たに生成されたjson自体は開発などの確認用にリポジトリにも入れて欲しいのでその辺りも工夫しないといけませんね

**Comment by HyodaKazuaki** [comment]
Googleスプレッドシートからjsonを取得する方法をいろいろ調べてみましたが、スプレッドシートの設定は特に難しいことはなさそうです
https://dev.classmethod.jp/articles/google_app_script_spreadsheet_ios/
この記事の「アプリの実装」手前までが手順です
GETアクセスの時に渡すパラメータをGASで受け取ることができるので、1つのファイルに複数のシートを入れて、パラメータで取り出すデータを選ぶこともできます
あとはデータにアクセスするプログラムなどを用意すれば良さそうです

**Comment by nomunomu0504** [comment]
とりあえず、非公開のスプレッドを作成します。リンク自体はSlackの方で流します。

**Comment by nomunomu0504** [comment]
スプレッドからデータを読み込み処理をproductionにマージ。動作確認済み。経過観察中...

あとは、更新hooksの部分をどうするか

**Comment by HyodaKazuaki** [comment]
> あとは、更新hooksの部分をどうするか

Slackから更新したいのであれば、JavaScriptでSlackのbotを作る方法がいいかもですね
https://qiita.com/ref3000/items/83b36541f61e334b542e
スプレッドシートの更新のたびに実行してよいのであれば、スプレッドシートの設定に「更新がされた場合はメールアドレスに通知する」という機能があるので、そのメールを受信して実行するスクリプトを作る方法があります
https://www.appsupport.jp/docs/notification/

**Comment by satackey** [comment]
> <https://github.com/nomunomu0504/covid19/issues/48#issuecomment-607343528>
> それなら、JSとかでcron設定して動作させるのが濃厚かな〜
> 
> > そのため、Googleのスプレッドシートを用いてデータを管理し、そこからJSONデータを構築して表示させたい。更新頻度は30min/回（42回/日）

この自動更新の話なのですが、Slackのupdatejsonコマンドで起動させている、[workflowはスケジュールで動かせる](https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule)ので、自動でPRのMergeができるようにすれば実現できそうです。

ただ1つ問題があって、PRの送り先は`nomu_development`ですけど、本番環境は`nomu_production`なので、現在の運用では自動PRのMerge後にもう一度Mergeをしないといけません。

そこで提案です！現在の`nomu_development`での動作確認をトピックブランチ上のNetlifyプレビューに移行し、PRは直接`nomu_production`へ出すフローはどうでしょうか？

**Comment by HyodaKazuaki** [comment]
`update_fukui_data/YYYYMMDD_HHhMMmSSs`ブランチが作成されるのであれば、`nomu_development`ブランチと`nomu_production`ブランチの両方にPR出すのはいかがでしょうか

同じコミットをマージするので、`nomu_development`ブランチから`nomu_production`ブランチへのマージにも対応できるのではないかと思います

**Comment by satackey** [comment]
一度それも考えたんですけど、READMEを見ていると`nomu_development`ブランチは「開発の検証が目的」という感じで、Netlifyがあるならコンフリクトの心配もないですし、1個ずつ動作確認できるのでベターなのかなと思ってます。(自動PRマージの話がなかったとしても、トピックブランチのプレビュー&動作確認に比べて、`nomu_development`を運用するメリットよりも手間が大きくなるのでは🤔という)

(もう一つ、理論上はマージできるのはそうなのですが、gitの履歴が見えづらくなりそうなのがちょっとつらいなと個人的に思いました)

**Comment by nomunomu0504** [comment]
まだnetlifyの方から連絡がないのですが、連絡がきたら、メインをnetlifyにして、バックアップをVPSにしようと思ってます。そうなった場合、netlifyがnomu_production, VPSがnomu_developmentになります。

とはいえ、そうすると検証用どうするんだって話なので、VPSのバックアップ用をdev用にしてもいいのかなとも思ってますが...

**Comment by satackey** [comment]
検証用のサイトなんですが、PRを作った時に、Netlifyがビルドして`https://deploy-preview-{プルリクエストの番号}--determined-knuth-125b23.netlify.com`にプレビューしてくれるので、これを検証に使うといい感じになりそうだなと思っています。(「トピックブランチのプレビュー」で伝わってなかった(？)感じでごめんなさい🙏)

**Comment by HyodaKazuaki** [comment]
> 検証用のサイトなんですが、PRを作った時に、Netlifyがビルドして`https://deploy-preview-{プルリクエストの番号}--determined-knuth-125b23.netlify.com`にプレビューしてくれるので、これを検証に使うといい感じになりそうだなと思っています。(「トピックブランチのプレビュー」で伝わってなかった(？)感じでごめんなさい🙏)

これは`production`の動作をしますか？

**Comment by satackey** [comment]
現在は`yarn generate:dev`でのプレビューですが、`yarn generate:deploy`をプレビューさせることも可能です。
(「`production`の動作」の意味はこれで合ってます？)

**Comment by HyodaKazuaki** [comment]
あってます！
なるほど、こっちのほうが金銭的コストも減らせて良さそうですね

**Comment by nomunomu0504** [comment]
なるほど。理解した笑、老害おじさんは理解が遅いので...🙄

ということは、VPSいらないって話になってくる的な？👀

**Comment by satackey** [comment]
`データの更新`と`UIの変更`を分離できないか考えているんですけど、ビルド時にJSONからのデータを埋め込むのではなくて、ページの読み込み時にJSONをfetchしてくるのはどうですかね？APIみたいな感じで。

**Comment by nomunomu0504** [comment]
こっちも完了してそうだけど、Closeでよき？
@HyodaKazuaki

**Comment by HyodaKazuaki** [comment]
Googleスプレッドシートにお知らせを移行できたのでClose
