### ISSUE TITLE
サイトのauthorが福井県になっている

### ISSUE THREAD

**Issue by HyodaKazuaki** [nomunomu0504/covid19#49]
## 改善詳細 / Details of Improvement
- HTMLのmetaタグにauthorが入っているが、このサイトは非公式であるため「福井県」は不適切ではないか

## スクリーンショット / Screenshot
```html
<meta data-n-head="ssr" data-hid="author" name="author" content="福井県">
```
![image](https://user-images.githubusercontent.com/17569894/78040429-60916f80-73aa-11ea-81f6-0796ff1ea102.png)

## 期待する見せ方・挙動 / Expected behavior
- 非公式であることがわかる団体名など

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by nomunomu0504** [comment]
productionへの直接コミットで修正
