### ISSUE TITLE
一部のカードデータがずれている

### ISSUE THREAD

**Issue by nomunomu0504** [nomunomu0504/covid19#57]
## 起こっている問題 / The Problem
- 一部のカードに表示されているデータが１日遅れて表示されている。現状だと4/1が表示されていないといけないが、3/31のデータまでしか表示されていない

## スクリーンショット / Screenshot
- データ更新日は4/1だが、表示されているデータは3/31まで
![image](https://user-images.githubusercontent.com/11400588/78110894-bf9cc600-7436-11ea-8d20-e45cf6a8ba71.png)

## 期待する見せ方・挙動 / Expected Behavior
- データが存在する場合、一番最新のデータを表示させるようにする

## 起こっている問題の再現手段 / Steps to Reproduce
1. Topページを表示させる

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by HyodaKazuaki** [comment]
時刻データが8時UTCなので、当日分は午後5時に更新されます。
常に当日の最新データを表示するのであれば、次の2のどちらかの方法を取る必要があります。
1. データの時刻を前日の午後3時にする
2. データの時刻フォーマットをJSTにする

1についてはjsonデータでは前日に見えるのでわかりづらいと思います。
なので、2の時刻フォーマットをJSTにするのが得策ではないかと考えます。

**Comment by nomunomu0504** [comment]
たぶん２が得策なのは間違いないんだろうけど、サーバーの時刻も間違ってるわけではないし...。なぜだって感じだね。

予想だけど、コード内のDate変換メソッドがUTC系なんじゃないかと疑ってます。
また時間があるときに確認してみますが。

**Comment by HyodaKazuaki** [comment]
JavaScriptのDateは比較などをUTCで行うようで、環境のタイムゾーンをAsia/Tokyoにしても内部ではUTCで比較しているようです。
環境のタイムゾーンを認識するのは`toString()`などのメソッドだけで、比較や`toJSON()`ではUTCのままです。
幸運なことに、JSTのISO 8601形式データはちゃんと認識してUTCの時刻をずらしてくれるようなので、JSONファイルの時刻フォーマットをいじるだけで対応できると思います。

**Comment by HyodaKazuaki** [comment]
ただ、`2020-03-31T08:00:00.000Z`を`2020-03-31T08:00:00.000+0900`にするだけでは、午前8時JSTにならないと更新されないので、日付が変わってからは表示して欲しいのであれば`2020-03-31T00:00:00.000+0900`と時刻も変更する必要があると思います。
