### ISSUE TITLE
病床数を表示するグラフがあるとわかりやすい

### ISSUE THREAD

**Issue by HyodaKazuaki** [nomunomu0504/covid19#6]
## 改善詳細 / Details of Improvement
- 厚生労働省が公開しているオープンデータの一つ「感染症指定医療機関の指定状況」に記載されている福井県内の病床数を表示する
- 現在の入院患者数とセットでグラフ表示し何割程度病床が埋まっているかわかりやすくする

## スクリーンショット / Screenshot
![使用率例](https://user-images.githubusercontent.com/17569894/77528185-d8eec100-6ed0-11ea-8f39-9127d5d33710.png)
画像: [COVID-19 Japan - 新型コロナウイルス対策ダッシュボード](https://www.stopcovid19.jp/)
![カード例](https://user-images.githubusercontent.com/17569894/77528336-19e6d580-6ed1-11ea-9bf7-9cd0525bbfe2.png)
画像: [兵庫県内の最新感染動向 | 兵庫県非公式 新型コロナウイルスまとめサイト](https://stop-covid19-hyogo.org/)

## 期待する見せ方・挙動 / Expected behavior
- スクリーンショット2枚目のようなカードにグラフなどで入院患者数、残り病床数を表示する

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by nomunomu0504** [comment]
それを表示させるかどうかちょっと悩んでるんだよねーーー。どうしようか🤔

**Comment by HyodaKazuaki** [comment]
病床数はあった方がポータルサイトとしてはわかりやすいと思います
もしくは新型コロナウイルス対策ダッシュボードにリンクを貼るとかですね

**Comment by nomunomu0504** [comment]
https://www.facebook.com/hiroki.nomura.504/posts/1455261604648721?comment_id=1455296231311925&reply_comment_id=1455305747977640
