### ISSUE TITLE
マスクの在庫状況を地図上に表示したい

### ISSUE THREAD

**Issue by stshsn** [nomunomu0504/covid19#614]
## 改善詳細 / Details of Improvement
- 福井県があっせんするマスクの販売が開始されるにあたって店舗ごとの在庫状況を表示したい

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/34150349/79731861-d778b300-832d-11ea-81e9-ae29493e4764.png)

## 期待する見せ方・挙動 / Expected behavior
- 地図上の店舗マーカーをクリックすると店舗の在庫状況が表示される
- もしくは地図上に表示されている店舗すべての在庫一覧を右側にテーブルで表示する
- 後者の場合はある程度店舗数が絞られてから表示したほうがよいかも

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by nomunomu0504** [comment]
在庫は表示しない方向になったのでclose, 別issueを参照（ #755 ）
