### ISSUE TITLE
速報カードの更新時刻が表示されているデータよりも前になっている

### ISSUE THREAD

**Issue by HyodaKazuaki** [nomunomu0504/covid19#62]
## 起こっている問題 / The Problem
- 速報カードの更新時刻が、カード内の速報データの日付よりも前になっている
    - 2020年3月30日 16時更新なのに2020/04/01のデータが差し込まれている

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/17569894/78156537-e6302080-7479-11ea-8800-e97c1388d44a.png)

## 期待する見せ方・挙動 / Expected Behavior
- 更新時刻を変更する

## 起こっている問題の再現手段 / Steps to Reproduce
1. サイトにアクセスする

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by nomunomu0504** [comment]
すいません。それは僕の更新ミスです...🙇‍♂️

**Comment by HyodaKazuaki** [comment]
#68 で`nomu_production`に対して修正

**Comment by HyodaKazuaki** [comment]
マージされたのでcloseします
