### ISSUE TITLE
速報の件数が多い

### ISSUE THREAD

**Issue by HyodaKazuaki** [nomunomu0504/covid19#63]
## 改善詳細 / Details of Improvement
- 速報カードに表示されている情報が多く感じる
- 速報カードなどでグラフなどがどんどん下にいってしまっている

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/17569894/78156661-0d86ed80-747a-11ea-9ec1-0dda26d0046b.png)

## 期待する見せ方・挙動 / Expected behavior
- 件数をもう少し絞る
    - 個人的には前日までの情報を速報として表示するだけで良いと思います

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by nomunomu0504** [comment]
こっから溢れたやつはnews.jsonに追記していく形を取ってます。時間見つけて移動しておきます。

**Comment by HyodaKazuaki** [comment]
現時点では速報データはカードに直書きしているので、これを`news.json`とまとめるなどしてGoogleスプレッドシートで管理し取得させる方法に変更した方が良さそうですね
#48 に含めて同じ方式をとりましょうか

**Comment by nomunomu0504** [comment]
スプレッドシートで管理することになったので終了します。
