### ISSUE TITLE
グラフデータと更新日時のソースが別のファイルになっている

### ISSUE THREAD

**Issue by stshsn** [nomunomu0504/covid19#65]
## 起こっている問題 / The Problem
- 「陽性患者数」カードのグラフデータと更新日時のソースが別ファイル
- グラフデータは data/patients_summary.json
- 更新日時は data/patients.json

## 期待する見せ方・挙動 / Expected Behavior
- どちらも data/patients_summary.json から取得する
- 可能であれば data/patients_summary.json の 'date' もタイムゾーン込みの表記に

## 起こっている問題の再現手段 / Steps to Reproduce
1. Topページを表示

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by nomunomu0504** [comment]
作業できそうであれば、自分で自分をアサインして進めてもらっても大丈夫です！
コラボレーター権限があるので、ある程度操作権限はあると思います！
