### ISSUE TITLE
ゲンキーの地図カードから在庫状況の表示を無効化する

### ISSUE THREAD

**Issue by HyodaKazuaki** [nomunomu0504/covid19#674]
## 起こっている問題 / The Problem
- マスク販売時の混乱を避けるため、ゲンキーの地図カードから在庫状況の表示を消す

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/17569894/79986360-e5256880-84e6-11ea-8244-88506963f840.png)

## 期待する見せ方・挙動 / Expected Behavior
- 暫定として店名のみを表示する

## 起こっている問題の再現手段 / Steps to Reproduce
1. サイトにアクセスする
2. ゲンキーの地図カード上のピンのうち、いずれかにマウスオーバーする

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by HyodaKazuaki** [comment]
対応済みのためclose

**Comment by nomunomu0504** [comment]
すまん笑、直接プッシュしてしまったわ。ありがとう
