### ISSUE TITLE
病床使用率グラフの色をパーセンテージに応じて変化させたい

### ISSUE THREAD

**Issue by nomunomu0504** [nomunomu0504/covid19#69]
## 改善詳細 / Details of Improvement
- 視覚的に分かるように率が上がれば色を赤系統で表示させたい

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by HyodaKazuaki** [comment]
@stshsn がPRしてくださったコードでは3段階で色が変化していますが、 @nomunomu0504 のイメージはどのような感じですか？
私は段階の他に、割合が上がると徐々に色が赤くなる(つまり割合が赤色の濃さ)ものを想像していました

**Comment by nomunomu0504** [comment]
@HyodaKazuaki 
僕的には視覚的に分かればいいと思っているので、濃度がライナーで変化するかどうかは任せるつもりでした。これで問題ないと思います！

@stshsn 
作業ありがとうございます！作業始めるときに issue に作業を始める旨を一言書いていただけると、進捗が分かるのでありがたいです！あと、issue の担当者（assigner）を自分自身に設定することも、合わせてお願いいたします！

**Comment by stshsn** [comment]
@nomunomu0504 
> 作業始めるときに issue に作業を始める旨を一言書いていただけると、進捗が分かるのでありがたいです！あと、issue の担当者（assigner）を自分自身に設定することも、合わせてお願いいたします！
そうですね。次からそうします。
