### ISSUE TITLE
検査実施人数のカードタイトルが不正確

### ISSUE THREAD

**Issue by HyodaKazuaki** [nomunomu0504/covid19#7]
## 起こっている問題 / The Problem
- 検査実施人数のカードタイトルが`検査実施人数（累計）`となっているが、日別も表示できるため`検査実施人数`の方が正しい

## スクリーンショット / Screenshot
![検査実施人数（累計）](https://user-images.githubusercontent.com/17569894/77531321-13a72800-6ed6-11ea-9320-af94f4a2dcac.png)

## 期待する見せ方・挙動 / Expected Behavior
- カードタイトルを`検査実施人数`とする

## 起こっている問題の再現手段 / Steps to Reproduce
1. トップページにアクセスする
2. 検査実施人数（累計）`のカードを見る

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by HyodaKazuaki** [comment]
あと、`日別`と表示されているのも不自然ですね
どちらかといえば`週別`でしょうか

**Comment by HyodaKazuaki** [comment]
これはすぐ対応できるのでやりますね

**Comment by nomunomu0504** [comment]
本番サイトに適用しました
