### ISSUE TITLE
githubリポジトリへのリンク間違い

### ISSUE THREAD

**Issue by hiddenxv** [nomunomu0504/covid19#75]
## 起こっている問題 / The Problem
当サイトについてページの、githubへのリンクが間違っている

**Comment by nomunomu0504** [comment]
@hiddenxv 
ありがとうございます。ほんとですね。気が付きませんでした。

**Comment by hiddenxv** [comment]
いま修正してPRだしますねー

**Comment by nomunomu0504** [comment]
よろしくお願いします！

**Comment by hiddenxv** [comment]
って、権限ないかもｗ

**Comment by nomunomu0504** [comment]
コラボレーター招待しておきましたので、たぶんできるかと！
