### ISSUE TITLE
陽性患者数の日別表示ボタンが週別と表示されている

### ISSUE THREAD

**Issue by HyodaKazuaki** [nomunomu0504/covid19#77]
## 起こっている問題 / The Problem
- 陽性患者数カードの日別/累計を切り替えるボタンが、週別と表示されている

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/17569894/78270231-8606b080-7545-11ea-80fb-e391f5b06efe.png)

## 期待する見せ方・挙動 / Expected Behavior
- このカードだけ日別と表示する

## 起こっている問題の再現手段 / Steps to Reproduce
1. サイトにアクセスする

## 関連する issue / Related Issues
- #7  

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by nomunomu0504** [comment]
あれ、これ前回直したんだっけ？
あれは別のカードか？

**Comment by HyodaKazuaki** [comment]
あの時に`日別`を`週別`にしたんですが、他のカードも全部変更されてしまったんです
なので今回はこのカードだけ日別となるように`components/DataSelector.vue`を変更しないといけません
`components/DataSelector.vue`とほとんど同じな別のvueを作ってもいいかもです

**Comment by nomunomu0504** [comment]
そういうことか。理解した。

**Comment by stshsn** [comment]
調査して対応してみます。

**Comment by nomunomu0504** [comment]
@stshsn 
よろしくお願いします！！

**Comment by stshsn** [comment]
inspection_persons.json の中身が undefined になっていてローカルのテストができないんですがサンプルありますか？

**Comment by HyodaKazuaki** [comment]
@stshsn 
`covid19_fukui/`に移動してもらって
```bash
$ node json_getter.js
```
を実行してもらえばデータを生成できると思います

**Comment by stshsn** [comment]
@HyodaKazuaki 
やってみます。

**Comment by stshsn** [comment]
@HyodaKazuaki 
できました！
