### ISSUE TITLE
感染症病床使用率カードのグラフカラーがサイトのテーマカラーと合っていない

### ISSUE THREAD

**Issue by HyodaKazuaki** [nomunomu0504/covid19#771]
## 改善詳細 / Details of Improvement
- 感染症病床使用率カードの円グラフに採用されているカラーが緑色であり、他のグラフで採用されている青色に統一されていない

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/17569894/80285962-8e789280-8763-11ea-8cda-68611dfac420.png)

## 期待する見せ方・挙動 / Expected behavior
- 他のグラフと同様に色を統一する

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by nomunomu0504** [comment]
これに関しては、安全、注意、要注意みたいな色を現したかったので
「緑」「黄」「赤」でいいのかなって感じなんですが、どうでしょうか？

「青」「黄」「赤」にしても問題ないかな？🤔

**Comment by HyodaKazuaki** [comment]
あー！そうでしたね
確かに「安全」という意味では緑も青も良さそうです
JIS安全色によると
> 安全色：緑
>
> 意味や目的：安全状態、進行、完了・稼働中

> 安全色：青
>
> 意味や目的：指示、誘導、安全状態、完了・稼働中

https://iro-color.com/episode/jis.html
だそうですので、どちらでも良いかな？と思います
ただ、サイト全体が青系で統一されていたので、この場合だったら段階的に色分けしていることを表記するのもいいかもしれないですね

**Comment by nomunomu0504** [comment]
なるほどですね。グラフの注釈に入れますか。

そして、青色にしておきます。
