### ISSUE TITLE
検査陽性者の状況が正しくない

### ISSUE THREAD

**Issue by HyodaKazuaki** [nomunomu0504/covid19#84]
## 起こっている問題 / The Problem
- 死亡1名 退院0名のはずが死亡0名 退院1名となっている

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/17569894/78334809-61ebb380-75c7-11ea-8994-cd5c8ac1a7ff.png)

## 期待する見せ方・挙動 / Expected Behavior
- 死亡1名 退院0名とする

## 起こっている問題の再現手段 / Steps to Reproduce
1. サイトにアクセスする

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by nomunomu0504** [comment]
googleのスプレッドとスクリプトは問題なさそうだから、ほかのところ？

**Comment by nomunomu0504** [comment]
JSONも問題なかった

**Comment by stshsn** [comment]
おそらく、JSONの退院と死亡の順番が逆じゃないかと。

**Comment by stshsn** [comment]
https://github.com/nomunomu0504/covid19/blob/14284ea4cbb0ae171c7bcbe9121af8398395e806/utils/formatConfirmedCases.ts#L51-L61

`attr` は見てなくて、配列の順番だけを見てるのではないかと思います。

**Comment by nomunomu0504** [comment]
あら。マジか。修正します！
ありがとうございます！

**Comment by nomunomu0504** [comment]
直接コミットで修正入れました。報告と確認ありがとうございました。
@HyodaKazuaki @stshsn
