### ISSUE TITLE
Safariで一部のグラフが表示されない

### ISSUE THREAD

**Issue by HyodaKazuaki** [nomunomu0504/covid19#85]
## 起こっている問題 / The Problem
- Safariで一部のグラフが表示されずデータのみになる
    - 陽性患者数カードのグラフが該当
    - PCR検査件数も？
    - 関連Issue #11 
    - ~~陽性患者数カードページは何も表示されない~~ → 修正済み PR: #90
        - ~~https://covid19-fukui.com/cards/number-of-confirmed-cases~~

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/17569894/78359568-447f0f80-75f0-11ea-8904-08d6ec3a700f.png)

## 期待する見せ方・挙動 / Expected Behavior
- Safariでもグラフが表示される

## 起こっている問題の再現手段 / Steps to Reproduce
1. サイトへアクセスする

## 動作環境・ブラウザ / Environment
- macOS / iOS / Windows
- Safari / iOS版Google Chrome / Internet Explorer

**Comment by HyodaKazuaki** [comment]
## エラーログ / Error log
![image](https://user-images.githubusercontent.com/17569894/78382390-c03d8400-7611-11ea-83da-8a1b9b3b05e8.png)

**Comment by HyodaKazuaki** [comment]
原因が判明したので報告します
直接的な原因となるコミットは #64 のjsonデータでした
JSONの日付はISO 8601で記述されていますが、タイムゾーンをJSTにする場合は`+0900`でなく`+09:00`とする必要があります
ChromeやFirefoxなどのブラウザはこれらをうまく認識して処理してくれますが、Safariなどのブラウザはこれらの認識が厳格であるため動作しませんでした

JSONデータはスプレッドシートからデータを取得してきているので、該当スプレッドシートの日付表記を修正することで対応が完了します
@stshsn による発見と素晴らしい貢献に感謝します！

**Comment by nomunomu0504** [comment]
おおー！！なんと！！

@stshsn 
ありがとうございます！！感謝します！

@HyodaKazuaki 
と、このissueクローズしてるけどいいの？笑

**Comment by HyodaKazuaki** [comment]
今スプレッドシートの対応をしています
次に本番環境でデータを引っ張ってくればグラフは正常になるはずです
