### ISSUE TITLE
トップページに福井新聞社のRSSを表示

### ISSUE THREAD

**Issue by FooQoo** [nomunomu0504/covid19#96]
## 目的
- 感染動向の情報鮮度は[福井県の新着情報](https://www.pref.fukui.lg.jp/)より[福井新聞社](https://www.fukuishimbun.co.jp/list/feed/rss)の方が良い
- RSSフィードをトップページに表示する

## 改善詳細 / Details of Improvement
- 福井県の新着情報と同じモジュールで福井新聞社のRSSを表示する
- UIは他のお知らせモジュールと同一
- 一旦リリースし、福井県のRSS含め、あとでUIの改善を行う方針

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/14051784/78466057-faa14100-7737-11ea-8933-04e6cbfe1d62.png)

## 期待する見せ方・挙動 / Expected behavior
- 各RSSフィードの内容は、「時刻 タイトル \n 説明」

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by nomunomu0504** [comment]
ここまで頭の部分が多くなってくると、グラフとかまでたどり着くのにスクロール数が増えてしまうので、スマホユーザーのUX的にはどうだろうと考える必要がありそうですね。

**Comment by FooQoo** [comment]
@nomunomu0504 
そうですね、以下モジュール削減の案を提案いたしますがいかがでしょう？

## 削減モジュール
- 最新のお知らせ (県内)
- 最新のお知らせ (国内)
![image](https://user-images.githubusercontent.com/14051784/78466217-a13a1180-7739-11ea-906f-66aef76736e7.png)

## 理由
- サイドメニューで上記モジュールの専用ページがあり、導線は残るため
- 更新頻度が少なく、形骸化しつつあるため

**Comment by HyodaKazuaki** [comment]
県内のお知らせには速報データから古くなったデータを挿入していますので、速報カードが残っていれば導線確保のみでトップの表示は廃止してもいいかなと思います

**Comment by nomunomu0504** [comment]
なるほど。では、その方向で修正しましょう。

@FooQoo 
お手数かけますが、再度修正の方よろしくお願いします！
