### ISSUE TITLE
トップページ右上のテキストが見切れる

### ISSUE THREAD

**Issue by mimikun** [nomunomu0504/covid19#98]
## 改善詳細 / Details of Improvement
- トップページ右上のテキストが微妙に見切れており、読みにくい

## スクリーンショット / Screenshot
<img src="https://user-images.githubusercontent.com/13450321/78468388-8031ea80-7752-11ea-8082-4e8691d688f5.PNG" width="420px">

## 期待する見せ方・挙動 / Expected behavior
- 適切にテキストサイズを縮小させて表示させたい

## 動作環境・ブラウザ / Environment
- iOS 13.4 / iPhone Xs
- Safari

**Comment by HyodaKazuaki** [comment]
## 原因
調査したところ、文章の横にある福井県のロゴ画像が大きすぎることが原因であることがわかりました
## 解決策
文字をこれ以上小さくするのは可読性が下がることや、画像が大きい割に画像自体にそこまで重要な情報を含んでいないことから、画像を小さくしたものを使用することにします
