### ISSUE TITLE
パクリならパクリともっとわかりやすくしろ！という人のために

### ISSUE THREAD

**Issue by MCGILLIS-FAREED** [nomunomu0504/covid19#99]
## 改善詳細 / Details of Improvement
- これを追加していただきたい
![](https://user-images.githubusercontent.com/63182144/78468618-9f317c00-7754-11ea-94d8-4ea1f396a4f4.png)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by nomunomu0504** [comment]
いやー、小さい規模なら入れたかったんですけどねーーー🙄笑

今回は規模と内容が内容なので、延期しておきます🙇‍♂️
